Error: trim() expects parameter 1 to be string, array given - library/Zend/Http/Client.php:1127
We have seen occasions where the location header is returned as an array, but the code assumes we'll be dealing with a string, so check for that and reset the array where applicable.